import { z } from "zod";

export const scenarios = [
  "connect",
  "create-prepared",
  "inspect",
  "exec-argv",
  "exec-shell",
  "exec-nonzero",
  "file-binary",
  "file-overwrite",
  "file-no-clobber",
  "inventory",
  "destroy",
  "confirm-cleanup",
  "close",
  "build-oci",
] as const;

const safeLabel = z
  .string()
  .min(1)
  .max(80)
  .regex(/^[a-zA-Z0-9_.: /-]+$/);

const evidence = z
  .string()
  .min(1)
  .max(240)
  .regex(/^[a-zA-Z0-9_.:/#-]+$/);

export const recordSchema = z.strictObject({
  schemaVersion: z.literal(1),
  provider: z.enum(["daytona", "e2b"]),
  scenario: z.enum(scenarios),
  mode: z.enum(["live", "fixture", "packed"]),
  status: z.enum(["passed", "failed", "not-run", "unsupported", "blocked"]),
  runCleanup: z.enum(["confirmed", "incomplete"]).optional(),
  sdkCommit: z.string().regex(/^[0-9a-f]{40}$/),
  sdkVersion: safeLabel,
  nativeVersion: safeLabel.optional(),
  runtime: safeLabel,
  platform: safeLabel,
  timestamp: z.iso.datetime({ offset: true }),
  configuration: z.strictObject({
    imageClass: z.enum(["prepared", "oci", "none"]),
    network: safeLabel,
    regionClass: safeLabel,
  }),
  evidenceRef: evidence.optional(),
  issue: z
    .enum([
      "missing-credentials",
      "not-authorized",
      "not-selected",
      "dependency-failed",
      "unsupported-capability",
      "assertion-failed",
      "outcome-unknown",
      "cleanup-unconfirmed",
      "interrupted",
    ])
    .optional(),
});

export const reportSchema = z
  .strictObject({
    schemaVersion: z.literal(1),
    records: z.array(recordSchema).max(1000),
  })
  .superRefine((report, ctx) => {
    for (const [index, record] of report.records.entries()) {
      if (record.mode === "live" && !record.evidenceRef)
        ctx.addIssue({
          code: "custom",
          path: ["records", index, "evidenceRef"],
          message: "Live records require evidence",
        });

      if (record.mode === "live" && !record.nativeVersion)
        ctx.addIssue({
          code: "custom",
          path: ["records", index, "nativeVersion"],
          message: "Live records require the pinned native version",
        });

      if (record.mode === "live" && !record.runCleanup)
        ctx.addIssue({
          code: "custom",
          path: ["records", index, "runCleanup"],
          message: "Live records require cleanup state",
        });
    }
  });

export type QualificationRecord = z.infer<typeof recordSchema>;

export type QualificationReport = z.infer<typeof reportSchema>;

export type Scenario = QualificationRecord["scenario"];

// oxlint-disable-next-line anti-slop/no-unknown-parameters -- This is the JSON artifact boundary; reportSchema parses it immediately.
export function parseReport(value: unknown): QualificationReport {
  return reportSchema.parse(value);
}

function key(record: QualificationRecord): string {
  return [
    record.provider,
    record.scenario,
    record.configuration.imageClass,
    record.configuration.network,
    record.configuration.regionClass,
    record.runtime,
    record.platform,
  ].join("|");
}

function markdownTable(header: string[], rows: string[][]): string[] {
  const widths = header.map((cell, index) =>
    Math.max(3, cell.length, ...rows.map((row) => row[index]?.length ?? 0)),
  );

  const line = (row: string[]) =>
    `| ${row.map((cell, index) => cell.padEnd(widths[index]!)).join(" | ")} |`;

  return [
    line(header),
    `| ${widths.map((width) => "-".repeat(width)).join(" | ")} |`,
    ...rows.map(line),
  ];
}

export function renderLiveMatrix(reports: readonly QualificationReport[]): string {
  const latest = new Map<string, QualificationRecord>();

  for (const report of reports)
    for (const record of parseReport(report).records) {
      if (record.mode !== "live") continue;
      const id = key(record);
      const previous = latest.get(id);

      if (
        !previous ||
        Date.parse(record.timestamp) > Date.parse(previous.timestamp) ||
        (Date.parse(record.timestamp) === Date.parse(previous.timestamp) &&
          ((previous.status === "passed" && record.status !== "passed") ||
            (previous.runCleanup === "incomplete" && record.runCleanup === "confirmed")))
      )
        latest.set(id, record);
    }

  const rows = [...latest.values()].sort((a, b) => key(a).localeCompare(key(b)));

  const lines = [
    "---",
    "title: Provider live qualification",
    "description: Dated evidence for tested provider operations and configurations.",
    "---",
    "",
    "<!-- Generated by provider-qualification/render.ts; do not edit by hand. -->",
    "",
    "Daytona and E2B are the qualification targets. This table reports measured operations only; distribution status is not a live pass.",
    "",
    "These results cover only the stated image, network and region classes. Fixture and packed tests do not establish live provider behavior. A later failure supersedes an earlier pass for the same configuration.",
    "",
  ];

  const tableRows = rows.map((record) => [
    record.provider,
    record.scenario,
    record.configuration.imageClass,
    record.configuration.network,
    record.configuration.regionClass,
    `${record.runtime} ${record.platform}`,
    `${record.sdkVersion} (${record.sdkCommit.slice(0, 8)}) / ${record.nativeVersion ?? "—"}`,
    record.runCleanup === "incomplete" && record.status === "passed"
      ? "incomplete (scenario passed)"
      : record.status,
    new Date(record.timestamp).toISOString().slice(0, 10),
    record.evidenceRef ? `[record](${record.evidenceRef})` : "—",
  ]);

  lines.push(
    ...markdownTable(
      [
        "Provider",
        "Scenario",
        "Image",
        "Network",
        "Region class",
        "Runtime",
        "SDK / native",
        "Latest live result",
        "Date",
        "Evidence",
      ],
      tableRows.length
        ? tableRows
        : [["—", "—", "—", "—", "—", "—", "—", "No live evidence recorded", "—", "—"]],
    ),
  );
  lines.push(
    "",
    "A missing row means no validated live result is recorded. Unsupported and blocked operations are not passes.",
    "",
  );

  return lines.join("\n");
}
